[package]
name = "nfa"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
clap = { version = "4.5.27", features = ["derive"] }
dirs = "6.0.0"
rand = "0.9.0"
serde = { version = "1.0.217", features = ["derive"] }
sled = "0.34.7"
tempfile = "3.16.0"
